# Generated by Django 5.1.7 on 2025-03-19 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
                ('cedula', models.IntegerField(max_length=50, unique=True)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('rol', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_client', models.IntegerField(max_length=50, unique=True)),
                ('nombre1_client', models.CharField(max_length=50)),
                ('nombre2_client', models.CharField(max_length=50, null=True)),
                ('apellido1_client', models.CharField(max_length=50)),
                ('apellido2_client', models.CharField(max_length=50, null=True)),
                ('id_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCrud.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caso', models.CharField(max_length=100)),
                ('descripcion_caso', models.CharField(max_length=255, null=True)),
                ('listo', models.BooleanField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCrud.clientes')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appCrud.usuarios')),
            ],
        ),
    ]
