# Generated by Django 5.1.7 on 2025-03-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula_client',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
